server:
  port: 8888

#配置文件在github
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/tang614/SpringcloudConfig/
#          username:
#          passphrase:
#          search-paths: /

#配置文件在本地

spring:
  cloud:
    config:
      server:
        native:
          search-locations: D:/config
  application:
    name: config-server
  profiles:
    active: native  # 配置使用本地储存

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/





