eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    # profile: test
    name: service-feign
# feign自带断路器
feign:
  hystrix:
    enabled: true


