spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: service-zipkin-hi
server:
  port: 1112
eureka:
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka/


