spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: service-zipkin-hello
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

